//
//  MovieDetailsRouter.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsRoutingNavigation {
    func showNewScreen()
}

protocol MovieDetailsDataPassing {
    var dataStore: MovieDetailsDataStore? { get set }
    func passDataToNextScene(segue: UIStoryboardSegue)
}

typealias MovieDetailsRouterInput = MovieDetailsRoutingNavigation & MovieDetailsDataPassing

class MovieDetailsRouter: MovieDetailsRouterInput {
    
    private struct Segues {
        static let ShowNextScreenIdentifier = ""
    }
    
    var dataStore: MovieDetailsDataStore?
    weak var viewController: MovieDetailsViewController?
    
    // MARK: Navigation
    
    func showNewScreen() {
        viewController?.performSegue(withIdentifier: Segues.ShowNextScreenIdentifier, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == Segues.ShowNextScreenIdentifier {
            // Pass Relevant Data
        }
    }
}
