//
//  MovieDetailsWorker.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class MovieDetailsWorker {

    let networkService = URLNetworkService(configuration: MovieDatabaseConfiguration.shared.apiConfiguration)

    func getMovieInformation(for movie: Movie, completion: @escaping (Swift.Result<GetVideosForMovieResponseModel, Error>) -> Void) {
        GetVideosForMovieOperation(movie: movie).execute(in: networkService, completion: completion)
    }
}
