//
//  MovieDetailsInteractor.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic {
    func doSomething(_ request: MovieDetails.Something.Request)
}

protocol MovieDetailsDataStore {
    //var name: String { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore {
    
    var presenter: MovieDetailsPresentationLogic?
    lazy var worker: MovieDetailsWorker? = {
        return MovieDetailsWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(_ request: MovieDetails.Something.Request) {
        worker?.doSomeWork()
        
        let response = MovieDetails.Something.Response()
        presenter?.presentSomething(response)
    }
}
