//
//  MovieListModels.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct MovieList {
    // MARK: Use cases

    let sortedPopularMovies: [Movie]

    struct FetchPopularMovies {
        struct Response {
            let popularMovies: [Movie]
        }

        typealias ViewModel = Response
    }

    struct SelectMovie {
        struct Request {
            let selectedMovie: Movie
        }
    }
}
