//
//  MovieListViewController.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListDisplayLogic: class {
    func displaySomething(_ viewModel: MovieList.Something.ViewModel)
}

class MovieListViewController: UIViewController, MovieListDisplayLogic {
    
    // MARK: - Properties
    var interactor: MovieListBusinessLogic?
    var router: MovieListRouterInput?
    
    // Mark: - Outlets
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        MovieListConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: - Do something
    
    func doSomething() {
        let request = MovieList.Something.Request()
        interactor?.doSomething(request)
    }
    
    func displaySomething(_ viewModel: MovieList.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
