//
//  MovieListInteractor.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListBusinessLogic {
    func doSomething(_ request: MovieList.Something.Request)
}

protocol MovieListDataStore {
    //var name: String { get set }
}

class MovieListInteractor: MovieListBusinessLogic, MovieListDataStore {
    
    var presenter: MovieListPresentationLogic?
    lazy var worker: MovieListWorker? = {
        return MovieListWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(_ request: MovieList.Something.Request) {
        worker?.doSomeWork()
        
        let response = MovieList.Something.Response()
        presenter?.presentSomething(response)
    }
}
