//
//  MovieListRouter.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListRoutingNavigation {
    func showNewScreen()
}

protocol MovieListDataPassing {
    var dataStore: MovieListDataStore? { get set }
    func passDataToNextScene(segue: UIStoryboardSegue)
}

typealias MovieListRouterInput = MovieListRoutingNavigation & MovieListDataPassing

class MovieListRouter: MovieListRouterInput {
    
    private struct Segues {
        static let ShowNextScreenIdentifier = ""
    }
    
    var dataStore: MovieListDataStore?
    weak var viewController: MovieListViewController?
    
    // MARK: Navigation
    
    func showNewScreen() {
        viewController?.performSegue(withIdentifier: Segues.ShowNextScreenIdentifier, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == Segues.ShowNextScreenIdentifier {
            // Pass Relevant Data
        }
    }
}
