//
//  MovieListConfigurator.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

extension MovieListViewController {
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(segue: segue)
    }
}

// MARK: - Connects View, Interactor, and Presenter
class MovieListConfigurator {
    
    static let sharedInstance = MovieListConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(_ viewController: MovieListViewController) {
        let presenter = MovieListPresenter()
        presenter.viewController = viewController
        
        let interactor = MovieListInteractor()
        interactor.presenter = presenter
        
        let router = MovieListRouter()
        router.viewController = viewController
        router.dataStore = interactor
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
