//
//  MovieListPresenter.swift
//  MovieRecommender
//
//  Created by Djordje Ljubinkovic on 9/22/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListPresentationLogic: LoadingLogic {
    func presentPopularMovies(_ response: MovieList.FetchPopularMovies.Response)
    func presentSelectedMovie()
}

class MovieListPresenter: MovieListPresentationLogic {
    var loadable: HasLoadingView? { return viewController }

    weak var viewController: MovieListDisplayLogic?

    // MARK: Presentation Logic
    func presentPopularMovies(_ response: MovieList.FetchPopularMovies.Response) {
        viewController?.displayPopularMovies(response)
    }

    func presentSelectedMovie() {
        viewController?.displaySelectedMovie()
    }
}
